name: test_pdf
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  pdfx: 2.0.1+2
  internet_file: 1.0.0+2
  pdf: ^3.8.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  syncfusion_flutter_barcodes: ^20.2.36






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

dependency_overrides:
  photo_view: ^0.14.0




flutter:

  uses-material-design: true

